version: 2.1

jobs:
  install-dependencies:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Update or install NPM
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: app-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  vercel-deploy:
    build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Install CLI Vercel
          command: 'sudo npm install -g vercel'
      - attach_workspace:
          at: .
      - run:
          name: Vercel Prod Deploy
          command: vercel --prod --build-env VITE_APP_BASEURL=https://rickandmortyapi.com/api/ --build-env VITE_APP_APIKEY=AIzaSyDfxe_66F_FuWb7d60AOoiWKFHk5WkMIFQ --build-env VITE_APP_AUTHDOMAIN=chat-9ddea.firebaseapp.com --build-env VITE_APP_PROJECTID=chat-9ddea --build-env VITE_APP_STORAGEBUCKET=chat-9ddea.appspot.com --build-env VITE_APP_MESSAGINGSENDERID=223834286296 --build-env VITE_APP_APPID=1:223834286296:web:e1aa09343f1c55a49c8fad --name $VERCEL_PROJECT_NAME --scope $VERCEL_SCOPE --token=$VERCEL_TOKEN --yes
  version: 2
  deploy-reactapp:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - develop
      - vercel-deploy:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - develop
